version: '3'
services:
  app:
    build: .
    volumes:
      - ./src:/work
      - ./dist:/dist
      - ./gopath:/gopath
    environment:
      - GO111MODULE=on
      - GOPATH=/gopath
    command: make build

